version: 0.2
phases:
  install:
    commands:
      - echo "Install phase — no dependencies needed"
  build:
    commands:
 - echo "Build succeeded for Prasiddha Silwal COSC2326"
      - echo "Week 11 — $(date)"
artifacts:
  files:
    - index.html
